// Export pages here
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as OAuth2Redirect } from './OAuth2Redirect'
export { default as Logout } from './Logout'
export { default as Dashboard } from './Dashboard'
export { default as Portfolios } from './Portfolios'
export { default as Watchlist } from './Watchlist'
export { default as Transactions } from './Transactions'
